apiVersion: apps/v1 # Define the API version for the StatefulSet resource
kind: StatefulSet # Specify the kind of resource
metadata:
  name: postgres # Name of the StatefulSet
spec:
  serviceName: postgres # Name of the service associated with the StatefulSet
  replicas: 1 # Number of replicas for the StatefulSet
  selector:
    matchLabels:
      app: postgres # Selector to match the labels of the pods
  template:
    metadata:
      labels:
        app: postgres # Labels for the pod template
    spec:
      containers:
      - name: postgres
        image: postgres:15 # Docker image for the PostgreSQL container
        volumeMounts:
        - mountPath: /var/lib/postgresql/data # Path where PostgreSQL data will be stored
          name: data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.postgres.storage }}
