apiVersion: apps/v1  # API version for StatefulSet
kind: StatefulSet  # Resource type
metadata:
  name: redis  # Name of StatefulSet
spec:
  serviceName: redis  # Service name
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: redis  # Label selector
  template:
    metadata:
      labels:
        app: redis  # Pod labels
    spec:
      containers:
      - name: redis  # Container name
        image: redis:7  # Redis image version
        ports:
          - containerPort: 6379  # Port number
        volumeMounts:
          - name: redis-data  # Volume name
            mountPath: /data  # Mount path
        resources:
          requests:
            cpu: "100m"  # CPU request
            memory: "128Mi"  # Memory request
          limits:
            cpu: "300m"  # CPU limit
            memory: "256Mi"  # Memory limit
  volumeClaimTemplates:
  - metadata:
      name: redis-data  # PVC name
    spec:
      accessModes: ["ReadWriteOnce"]  # Access mode
      resources:
        requests:
          storage: 2Gi  # Storage size
---
apiVersion: v1  # API version for Service
kind: Service  # Resource type
metadata:
  name: redis  # Service name
spec:
  clusterIP: None  # Headless service
  selector:
    app: redis  # Pod selector
  ports:
    - port: 6379  # Service port
      targetPort: 6379  # Target port
